<?php echo $this->doctype(); ?>

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/custom.min.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-social.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            ->prependFile($this->basePath() . '/js/custom.js')
            ->prependFile($this->basePath() . '/js/myScripts.js')
            ->prependFile($this->basePath() . 'https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . 'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/carousel.js',   'text/javascript', array('conditional' => 'lt IE 9',))

        ; ?>

    </head>
    <body>
   <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" id="icon_logo" href="<?php echo $this->url('home') ?>"><img id="logo" src="<?php echo $this->basePath('img/icon_home.png') ?>"></a>
                <a class="navbar-brand" id="name_logo" href="<?php echo $this->url('home') ?>">Open House</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav" id="nav-menu">
                    <li><a href="#"> Продажа</a></li>
                    <li><a href="#"> Аренда</a></li>
                    <li><a href="#">Новостройки</a></li>
                    <li><a href="#">Посуточно</a></li>
                 </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a  href="user"> <span class="glyphicon glyphicon-user"></span> Вход</a></li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">
        <div id="content">

            <?php echo $this->content; ?>
            
            <hr>
        </div> <!-- content -->
    </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
   <footer  class="navbar navbar-inverse  ">
       <div class="container">
           <div class="row">
               <div class="col-sm-6">
                   <h4><i class="fa fa-question-circle-o" aria-hidden="true"></i> Про нас</h4>

                        <p> Мы предлагаем профессиональные услуги и индивидуальный
                            подход к каждому клиенту. Мы постараемся подобрать недвижимость в Киеве по ценам и параметрам,
                            максимально отвечающим вашему запросу.
                        </p>

                        <p> Мы предлагаем профессиональные услуги и индивидуальный
                            подход к каждому клиенту. Мы постараемся подобрать недвижимость в Киеве по ценам и параметрам,
                            максимально отвечающим вашему запросу.
                        </p>

                        <p> Мы предлагаем профессиональные услуги и индивидуальный
                            подход к каждому клиенту. Мы постараемся подобрать недвижимость в Киеве по ценам и параметрам,
                            максимально отвечающим вашему запросу.
                        </p>
                </div>
                <div class="col-sm-3" id="contacts-footer">
                   <h4><i class="fa fa-map-marker" aria-hidden="true"></i> Контакты</h4>
                        <p><span class ="glyphicon glyphicon-home"></span>  Украина, Киев, пр. Маяковского, офис 4</p>
                        <p><span class ="glyphicon glyphicon-earphone"></span> +3 (8063)383-76-62</p>
                        <p><span class ="glyphicon glyphicon-envelope"></span> nikolayl@gmail.com</p>
                </div>

               <div class="col-sm-3" id="links-footer">
                   <h4><i class="fa fa-check-circle" aria-hidden="true"></i> Ссылки</h4>
                   <p><span class ="glyphicon glyphicon-star"></span><a> Сообщество нежвижимости</a></p>
                   <p><span class ="glyphicon glyphicon-star"></span><a> Форум недвижимости</a></p>
                   <p><span class ="glyphicon glyphicon-star"></span><a> Международное сообщество</a></p>
                   <p><span class ="glyphicon glyphicon-star"></span><a> Вакансии</a></p>

               </div>
           </div><!-- end row -->
           <div class="bottom-footer">
                <div class="col-md-5">Copyright &copy; 2016 {Nick}</div>

                <div class="col-md-7"
                     <ul id="footer-icons" >
                         <li><a class="btn btn-social-icon btn-vk">
                                 <span class="fa fa-vk"></span>
                             </a></li>
                         <li><a class="btn btn-social-icon btn-facebook">
                                 <span class="fa fa-facebook"></span>
                             </a></li>
                         <li><a class="btn btn-social-icon btn-instagram">
                                 <span class="fa fa-instagram"></span>
                             </a></li>
                         <li><a class="btn btn-social-icon btn-twitter">
                                 <span class="fa fa-twitter"></span>
                             </a></li>
                         <li><a class="btn btn-social-icon btn-vimeo">
                                 <span class="fa fa-vimeo"></span>
                             </a></li>
                     </ul>
                </div><!-- col-md-7 -->
           </div><!-- end bottom-footer -->
       </div>     <!-- end container -->
   </footer>
<?php echo $this->headScript() ->prependFile($this->basePath() . '/js/myScript.js');

?>

</html>
