    <div class="jumbotron">
        <div class="well">
            <?php
                $form->setAttribute('action', $this->url('application', array('action' => 'result')));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo '<fieldset><legend>Поиск по параметрам</legend>';
                /*foreach ($form as $element)
                {
                    echo '<div class="form-group">';
                    $attributes = $element->getAttributes();

                    $label = '';

                    if ($element->getLabel())
                    {
                        $element->setLabelAttributes(array('class' => 'col-lg-4 control-label'));
                        $label = $element->getLabel();
                            if(isset($attributes['required']))
                            {
                                $label .='&nbsp;';
                            }
                        $label = "<label class='col-sm-2 control-label'>{$label}</label>";
                    }

                    $type = isset($attributes['type']) ? $attributes['type'] : '';
                    $formElement = '';
            
                    switch ($type)
                    {
                        case 'select':
                            $formElement = $this->formSelect($element);
                        break;
                
                        case 'text':
                            $formElement = $this->formInput($element);
                        break;

                        default:
                            $formElement = $this->formRow($element);
                                $label = '';
                            break;
                   }
                        echo "{$label}<div class='col-sm-10'>{$formElement}</div>";
                        echo '</div>';
                }*/
                // echo $this->formRow($form->get('DialType'));
                echo $this->formRow($form->get('city'));
                //echo $this->formRow($form->get('district'));
                echo $this->formRow($form->get('submit'));
                echo '</fieldset>';
                echo $this->form()->closeTag();
            ?>
         </div>
    </div>
    <hr>
    <div class = "container">
        <div class ="row">
    <?php
        /*foreach ($this->posts as $post)
        {
            print '
            <div class="col-xs-9 col-md-9">
                 <div class = "thumbnail">
                     <div class="row">
                         <div class="col-xs-7 col-sm-5 col-md-4 col-lg-3" id="bor">
                             <img src="http://placehold.it/200x200" alt ="">
                         </div>

                         <div class="col-xs-4 col-sm-6 col-md-8 col-lg-9 " id="bor">
                             <div class ="caption">
                                 <h4><a href="'. $this->url('application', array('action'=>'view', 'id'=>$post['id'])).'">'. $post['name'].'</a></h4>
                                 <p> '.$post['text'].'</p>
                                 <p> Киев, Деснянский, ул. Маяковского 4, кв.312</p>
                                 <p> этаж  из  </p>
                                 <p> Площадь: 1 / 2 / 3 | общая / жилая / кухня </p>
                                 <a href="#" class ="btn btn-warning btn-xs">Подробнее <i class ="fa fa-arrow-right"></i></a>
                             </div><!-- end caption -->
                         </div>
                     </div>
                 </div>
             </div>
            
            
            ';
        }

*/
    foreach ($this->posts as $post)
    {
        echo $post['area_alive'];
    }
    ?>





            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12" id="block-right"> <!-- block-right -->
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Loren Ipsum</h4>
                        <hr>
                        <p class="list-group-item-text">bla bla blabla bla blabla bla blabla bla blabla bla blabla bla bla</p>
                    </a>

                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Loren Ipsum</h4>
                        <hr>
                        <p class="list-group-item-text">bla bla blabla bla blabla bla blabla bla blabla bla blabla bla bla</p>
                    </a>

                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Loren Ipsum</h4>
                        <hr>
                        <p class="list-group-item-text">bla bla blabla bla blabla bla blabla bla blabla bla blabla bla bla</p>
                    </a>
                </div><!-- list-group -->
            </div> <!-- block-right -->
         </div>
    </div>



